### ISSUE TITLE
ListImport system

### ISSUE THREAD

**Issue by NuckChorris** [hummingbird-me/hummingbird#710]
The ListImport system will form the basis of the MAL and Hummingbird importers in V3.  The goal is to make the addition of other site imports relatively simple by abstracting the details away.

An early version of ListImport was set up in V2 as a duck-typed enumerable, but in V3 I'll actually build a base class to provide a number of helpful abstractions.

The goal is to make it this easy to run an import:

``` ruby
# MyAnimeList
importer = ListImport::MyAnimeList.new(file)
LibraryEntry.import(user, importer) { |progress| user.notify(progress) }

# Anime-Planet
importer = ListImport::AnimePlanet.new(profile_url)
LibraryEntry.import(user, importer) { |progress| user.notify(progress) }

# Hummingbird
importer = ListImport::Hummingbird.new(file)
LibraryEntry.import(user, importer) { |progress| user.notify(progress) }
```

All while making it extremely easy to build new ones.
## Todo
- [x] Get an initial version of #709
- [x] Build a fuzzy matching system with a cutoff point
- [x] Build ListImport base class
- [x] Build `LibraryEntry.import`
- [x] Build ListImport child classes
  - [x] MyAnimeList
  - [x] MyDramaList
  - [x] Anime-Planet

**Comment by toyhammered** [comment]
Well feel free to add me to this, Ill be working on the MyAnimeList importer.
